Throw not exceptions, but return thy failures in peace.” - FP preacher

Try<Long> horrorFP(Data data) { // vavr.Try = specialized Either<Result,Exception>
  return process(data) 
    .onSuccess(e -> log.info(e))
    .flatMap(repo::save)
    .andThen(id -> audit(data));
}

Try<String> process(Data data) {
  if (data.name().isBlank()) 
    return Try.failure(new Ex("…"));
  return Try.success(data.name() + "!");
} 

// rewrite the above 2 functions throwing (runtime) exceptions
